# 코 자스립트

## 클래스

### 클래스 상속

> ❗️ 상속 다시 보기

### 정적 메서드와 정적 프로퍼티

- 클래스 함수 내 선언한 메서드 **정적(static)** 메서드
```javascript
class Animal {
  static legs = 4 { /* static */ }
  talk() { /* public */ }
  static talks() { /* static */ }
}
```
- 정적 메서드 내 `this === 클래스 생성자 자체(Animal)`
- **팩토리** 메서드
```javascript
class Animal {
  constructor(date) {
    this.birthday = date
  }
  static bear() {
    return new this(new Date())
  }
}
```
-  명시적 `extends Object` 상속
> ❗️ `extends` 의 역할 돌아보기
```javascript
/*
 * __proto__ 는 생성자 참조(?)
 * prototype 은 본문(?)
 */
class Animal {}
// Animal.prototype.__proto__ === Object.prototype
// Animal.__proto__ === Function.prototype
class Animal extends Object {}
// Animal.prototype.__proto__ === Object.prototype
// Animal.__proto__ === Object
```

### private, protected 프로퍼티와 메서드

- **public** : 어디서든 접근
- **private** : 클래스 내부 접근, 상속 불가, `this[#field]` 로 접근 불가 
```javascript
class Animal {
  #name = null /* private ('#' 문자로 시작) */
  #getName() {}
  name = null /* public, private 다른 필드로 취급 */
  getName()
}
```
- **protected** : 클래스(상속된, 자손) 내부 접근, 상속 가능
```javascript
class Animal {
  _name = null /* protected (암묵적으로 '_' 문자로 시작) */
  _getName() {}
}
```

### 내장 클래스 확장하기

```javascript
class Animal extends Array {
  // 내장 메서드는 반환 값에 명시된 클래스를 생성자로 사용
  static get [Symbol.species]() {
    return Array
  }
}
```

### 'instanceof'로 클래스 확인하기

- 상속 관계를 확인하는 `instanceof`, `*.prototype.isPrototypeOf(instance)`
```javascript
new Object instanceof Object // true
```
- `Class[Symbol.hasInstance]` 의 반환 값 === `instanceof` 결과
- 또는, 프로토타입 체인 상 프로토타입이 하나라도 일치하는지 확인

### 믹스인

- `Object.assign(대상, 재료)` 활용
```javascript
const sayHi = {
  sayHi() {}
}
class User {}

Object.assign(User.prototype, sayHi)
```

## 에러 핸들링

### 'try..catch'와 에러 핸들링

- 오직 **런타임 에러**에만 동작
- 동기적으로 동작
```javascript
try {
  /* 에러 없는 코드까지 실행 */
}
catch (error) {
  /* 에러 발생 시 싫행 */
  const { name, message, stack } = error
}
finally {
  /* ❗️ 항상 실행 */
}
```
- `throw` 연산자로 에러를 직접 `throw` 가능
```javascript
throw new Error('에러 지롱')
```
- `catch` 는 처리 불가능한 에러를 다시 `throw` 가능

### 커스텀 에러와 에러 확장

```javascript
/* 왜 다른 결과? */
class FooError extends Error {}
throw new FooError() // Uncaught Error 

function BarError() {}
Object.setPrototypeOf(BarError, Error)
throw new BarError() // Uncaught BarError
```
